### ISSUE TITLE
Task List 2

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/showcase#114]
- [ ] Tile styles look really bad.

- [ ] prepare pages/layout for flexbox - justify-content

- [ ] RenderGroceryById - rename, fix css, looks like it loads very slow.

- [ ] Move DepartmentInfo into new repository and connect it from there.(details upon request)

- [ ] We can grab and use some logic from MealCalendar project(details upon request)
