### ISSUE TITLE
todo-part1

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/showcase#171]
#133 

- [x] RenderContent. Separate(move away styles) from render method.
https://github.com/GroceriStar/showcase/blob/master/src/components/Cell/RenderContent.js#L28-L31
this is how it can be: https://github.com/GroceriStar/showcase/blob/master/src/components/Cell/Cell.js#L13-L16

- [x] we need to move getLink method to the router file. Right now we using an old version. Remove old versions(`important`), connect new version, test is it generate link properly
Check how we did with a similar problem: https://github.com/GroceriStar/showcase/blob/master/src/Router.js#L20-L22
https://github.com/GroceriStar/showcase/blob/master/src/components/Cell/RecipeHeader.js#L28

---

- [x] RecipeHeader  - move styles

- [x] RecipeLayout. Replace `getLink` method. move this into a separated component: https://github.com/GroceriStar/showcase/blob/master/src/components/Cell/RecipeLayout.js#L114-L161

sync your fork with our latest changes.

**Comment by Avuidrauxs** [comment]
@atherdon Thank you , I have begun. I am okay with the details and specifications given and will let you know if I have any blockers or questions.

**Comment by atherdon** [comment]
awesome! keep me posted

**Comment by atherdon** [comment]
get recipe link give you an ability to review single recipe
get link related to viewing data related to single grocery list.

right now please move styles into separated js object.(i mentioned it at task description)
sample:
https://github.com/GroceriStar/showcase/blob/master/src/components/Cell/Cell.js#L13-L16
```
const styles = {

   cursor: !maximized ? "pointer" : "auto"
}
```

**Comment by Avuidrauxs** [comment]
@atherdon okay I actually did move them into `scss` before but any reason why you prefer moving them into js objects?

**Comment by Avuidrauxs** [comment]
@atherdon  So you want me to move the `getLink` method into `Router`?

**Comment by Avuidrauxs** [comment]
@atherdon  Would this be an acceptable solution
```
<Link to={getLink(id)}>
         <Button type="primary" icon="right" size="large">
            View "{recipe.title}"
          </Button>
</Link>

```

**Comment by atherdon** [comment]
> @atherdon okay I actually did move them into `scss` before but any reason why you prefer moving them into js objects?

not a lot of reasons if it works now. it's briefly. if you want detailed explanation - create a separated issue and i'll explain it there.



> @atherdon So you want me to move the `getLink` method into `Router`?

yes



> @atherdon Would this be an acceptable solution
> 
> ```
> <Link to={getLink(id)}>
>          <Button type="primary" icon="right" size="large">
>             View "{recipe.title}"
>           </Button>
> </Link>
> ```

it depends... if you did everything clear and all links will work as they worked before - it's good for me

**Comment by Avuidrauxs** [comment]
@atherdon Review this PR , https://github.com/GroceriStar/showcase/pull/174

**Comment by atherdon** [comment]
Btw, what other components also have inline styles? let's update them too

**Comment by Avuidrauxs** [comment]
Unless I search through or do you have them marked already? @atherdon

**Comment by atherdon** [comment]
no, i didn't mark them. please check components manually.
but we need to finish dealing with our PR first

**Comment by atherdon** [comment]
ok, we solved issues from this task. i'll close it - but please review current components - it'll be also a good training for you and submit new PR if you'll find some hardcoded styles. then you can gid into #172 or update list of TODO(update only few of them for start) codelines
