### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/showcase#81]
- [ ] **flexbox layout for displaying data of GL in-old-fashion-way**
check different repos https://www.google.com.ua/search?q=react+flexbox+components&oq=reaqct+flexbox+components&aqs=chrome.1.69i57j0l2.11108j0j1&sourceid=chrome&ie=UTF-8

https://github.com/GroceriStar/showcase/issues/28
---
- [ ] **add styles to tile**
https://github.com/GroceriStar/showcase/issues/59
---
- [ ] **try to add sharing buttons**
i like this tool, but we should test if it suits well for us
https://github.com/SaraVieira/react-social-sharing

- [ ] [pdf][add flexboxes layouts]
Will share details upon request

**Comment by aanchirinah** [comment]
@atherdon , I want to take up the task for Enzyme Jest tests

**Comment by atherdon** [comment]
did you learn about how Jest+enzyme works, right? I mean not all of our members know how to use it, so i started to record some simple lessons. It's also not an easy task - because i didn't finish an explanation about what exactly should be done. But if you can take some time, explore this project and create a list about what shallow tests we should have here - it'll be awesome @aanchirinah

**Comment by aanchirinah** [comment]
@atherdon , I have used Enzyme + Jest before and I'm familiar with shallow tests thanks to Enzyme's documentation. So yes I can explore our project and list where we will need shallow tests.

**Comment by atherdon** [comment]
Good! Buzz me if you'll need help!
